This is a Fibonacci search of a function minimum.

Function `f(x)` must be unimodal, defined on interval `[a,b]`.

The goal is to find a minimum $f(x_{opt})$ within `[a,b]` with a given error $\epsilon $:

$|x_{opt}-x_{min}| < \epsilon $ from the true minimum $x_{min}$.

[Source of inspiration](http://mathfaculty.fullerton.edu/mathews/n2003/FibonacciSearchMod.html)

[Wolfram demo](http://demonstrations.wolfram.com/MinimumOfAFunctionUsingTheFibonacciSequence/)

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
def f(x, center = 25):
    return (x-center)**2

In [3]:
def Fnumber(n):
    return ((1+np.sqrt(5))**n - (1-np.sqrt(5))**n)/(2**n*np.sqrt(5))

In [4]:
Fnumber(np.arange(10))

array([ 0.,  1.,  1.,  2.,  3.,  5.,  8., 13., 21., 34.])

In [25]:
a = 0 #min of interval
b = 60 #max of interval
eps = 5 # error
n_fib = 1
while eps < (b-a)/Fnumber(n_fib) :
    n_fib += 1

n_iter_max = n_fib - 2
print('N(Fibonacci terms) = ' +str(n_fib))
print('n(iterations) = ' +str(n_iter_max))

N(Fibonacci terms) = 7
n(iterations) = 5


In [26]:
a_array = np.zeros(n_iter_max)
b_array = np.zeros(n_iter_max)
c_array = np.zeros(n_iter_max)
d_array = np.zeros(n_iter_max)

In [27]:
#first iter, k = 0, function f(x) is known in (a), (b)
k = 0
a_array[k] = a
b_array[k] = b
c_array[k] = a_array[k] + (b_array[k] - a_array[k])*(1 - Fnumber(n_fib - 1 - k)/Fnumber(n_fib - k))
d_array[k] = a_array[k] + (b_array[k] - a_array[k])*Fnumber(n_fib - 1 - k)/Fnumber(n_fib - k)

# two new function evaluations, (c) and (d)
if f(c_array[k]) <= f(d_array[k]):
    a_array[k+1] = a_array[k]
    b_array[k+1] = d_array[k]
else:
    a_array[k+1] = c_array[k]
    b_array[k+1] = b_array[k]
k += 1

#k=1
c_array[k] = a_array[k] + (b_array[k] - a_array[k])*(1 - Fnumber(n_fib - 1 - k)/Fnumber(n_fib - k))
d_array[k] = a_array[k] + (b_array[k] - a_array[k])*Fnumber(n_fib - 1 - k)/Fnumber(n_fib - k)

print(a_array.astype(int))
print(c_array.astype(int))
print(d_array.astype(int))
print(b_array.astype(int))

[0 0 0 0 0]
[23 13  0  0  0]
[36 23  0  0  0]
[60 36  0  0  0]


In [28]:
# only one(!) new function estimate, in (c) OR (d), the other is re-used
if f(c_array[k]) <= f(d_array[k]):
    a_array[k+1] = a_array[k]
    b_array[k+1] = d_array[k]
else:
    a_array[k+1] = c_array[k]
    b_array[k+1] = b_array[k]
k += 1
c_array[k] = a_array[k] + (b_array[k] - a_array[k])*(1 - Fnumber(n_fib - 1 - k)/Fnumber(n_fib - k))
d_array[k] = a_array[k] + (b_array[k] - a_array[k])*Fnumber(n_fib - 1 - k)/Fnumber(n_fib - k)

print(a_array.astype(int))
print(c_array.astype(int))
print(d_array.astype(int))
print(b_array.astype(int))

[ 0  0 13  0  0]
[23 13 23  0  0]
[36 23 27  0  0]
[60 36 36  0  0]


In [29]:
# only one(!) new function estimate, in (c) OR (d), the other is re-used
if f(c_array[k]) <= f(d_array[k]):
    a_array[k+1] = a_array[k]
    b_array[k+1] = d_array[k]
else:
    a_array[k+1] = c_array[k]
    b_array[k+1] = b_array[k]
k += 1

c_array[k] = a_array[k] + (b_array[k] - a_array[k])*(1 - Fnumber(n_fib - 1 - k)/Fnumber(n_fib - k))
d_array[k] = a_array[k] + (b_array[k] - a_array[k])*Fnumber(n_fib - 1 - k)/Fnumber(n_fib - k)

print(a_array.astype(int))
print(c_array.astype(int))
print(d_array.astype(int))
print(b_array.astype(int))

[ 0  0 13 13  0]
[23 13 23 18  0]
[36 23 27 23  0]
[60 36 36 27  0]


In [30]:
# only one(!) new function estimate, in (c) OR (d), the other is re-used
if f(c_array[k]) <= f(d_array[k]):
    a_array[k+1] = a_array[k]
    b_array[k+1] = d_array[k]
else:
    a_array[k+1] = c_array[k]
    b_array[k+1] = b_array[k]
k += 1

c_array[k] = a_array[k] + (b_array[k] - a_array[k])*(1 - Fnumber(n_fib - 1 - k)/Fnumber(n_fib - k))
d_array[k] = a_array[k] + (b_array[k] - a_array[k])*Fnumber(n_fib - 1 - k)/Fnumber(n_fib - k)

print(a_array.astype(int))
print(c_array.astype(int))
print(d_array.astype(int))
print(b_array.astype(int))

[ 0  0 13 13 18]
[23 13 23 18 23]
[36 23 27 23 23]
[60 36 36 27 27]


So, total number of `f(x)` evaluations is 7. If the interval `[0,60]` were divided into sub-intervals of length 5, the number of func. evaluations would be 12.